# User config
author: "Vishnu N K"
tagline: "Apps on Amazon Appstore"
# description: "In 1493, explorer Christopher Columbus found pineapples on Guadeloupe Island in the Caribbean. Pineapple on pizza soon followed..."
# keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "visnkmr@gmail.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: "/apps"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
